kiff_ecommerce:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: lwbnemr-sr28262
      user: Admin
      password: Mrken2172@@
      role: ACCOUNTADMIN
      database: Project
      warehouse: COMPUTE_WH
      schema: Analytics
      threads: 1
      client_session_keep_alive: false

    prod:
      type: snowflake
      account: lwbnemr-sr28262
      user: Admin
      password: Mrken2172@@
      role: ACCOUNTADMIN
      database: Linkedin
      warehouse: COMPUTE_WH
      schema: Analytics
      threads: 1
      client_session_keep_alive: false 