name: CI Workflow

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev 
  workflow_dispatch:

jobs:
  Test:
    name: 'Run unit test'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 

      - name: Set up dbt
        run: ./setup.sh
        shell: bash

      - name: install depenencies
        run: dbt deps   
        shell: bash

      - name: run dbt test
        run: dbt test   
        shell: bash


  goodbye:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Bye World"
        shell: bash
