version: 2

models: 
  - name: src_orders
    columns: 
      - name: O_ORDERKEY
        tests:
          - not_null
          - unique
          - dbt_utils.at_least_one
      - name: O_orderdate
        tests:
          - timestamp_is_not_present
  - name: src_customers
    columns: 
      - name: C_CUSTKEY
        tests:
          - not_null
          - unique
          # - relationships:
          #     to: ref('src_orders')
          #     field: O_CUSTKEY
